@startuml
'https://plantuml.com/object-diagram
!pragma layout smetana

object Main

object User{
- userId
- username
- password
- email
- role
}
object Cupcake{
- cupcakeID
- cupcakeName
- cupCakeBottom
- cupCakeTop
}
object CupcakeTop{
- topping
- price
}
object CupcakeBottom{
- flavour
- price
}
object UserMapper
object UserController
object CupcakeMapper
object CupcakeController
object UserValidator
object ConnectionPool
object SessionConfig
object ThymeleafConfig

Main -- UserController
Main -- CupcakeController
Main -- ConnectionPool
Main -- ThymeleafConfig
Main -- SessionConfig
UserController -- UserMapper
UserController -- User
UserMapper -- User
UserController -- UserValidator
CupcakeController -- CupcakeMapper
CupcakeController -- Cupcake
CupcakeMapper -- Cupcake
Cupcake -- CupcakeBottom
Cupcake -- CupcakeTop

@enduml
